/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Burger: typeof import('./components/Burger.vue')['default']
    DesktopNav: typeof import('./components/DesktopNav.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HomeHero: typeof import('./components/HomeHero.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    MobileNav: typeof import('./components/MobileNav.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    PortfolioCard: typeof import('./components/PortfolioCard.vue')['default']
    PortfolioItem: typeof import('./components/PortfolioItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
